name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
    with:
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        aws-region: us-east-2
        
      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain lunarclient --domain-owner 947665438472 --query authorizationToken --output text`
          echo "<settings><servers><server><id>lunarclient-private</id><username>aws</username><password>${CODEARTIFACT_AUTH_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn clean deploy -B
